source 'http://rubygems.org'

gem 'rails',   '3.1.1'
gem 'mongoid', '2.3.2'

group :assets do
  gem 'sass-rails',   '3.1.4'
  gem 'coffee-rails', '3.1.1'
  gem 'uglifier',     '1.0.4'
end

gem 'airbrake',         '3.0.4'
gem 'basic_assumption', '0.5.1'
gem 'bson_ext',         '1.4.1'
gem 'cancan',           '1.6.7'
gem 'devise',           '1.4.9'
gem 'dragonfly',        '0.9.8'
gem 'haml',             '3.1.3'
gem 'heroku',           '2.9.0'
gem 'jquery-rails',     '1.0.16'
gem 'nested_form',      '0.1.1', git: 'git://github.com/ryanb/nested_form.git'

group :development do
  gem 'haml-rails',   '0.3.4'
  gem 'ruby-debug19', '0.11.6'
  gem 'wirble',       '0.1.3'
end

group :development, :test do
  gem 'rspec-rails', '2.7.0'
  gem 'cover_me',    '1.2.0'
end

group :test do
  gem 'cucumber-rails',     '1.1.1'
  gem 'capybara',           '1.1.1'
  gem 'database_cleaner',   '0.6.7'
  gem 'delorean',           '1.1.0'
  gem 'email_spec',         '1.2.1'
  gem 'factory_girl_rails', '1.3.0'
  gem 'ffaker',             '1.8.1'
  gem 'launchy',            '2.0.5'
  gem 'mongoid-rspec',      '1.4.4'
end

group :staging, :production do
  gem 'thin', '1.2.11'
end